ibkr:
  host: "127.0.0.1"
  port: 7497
  accountId: "DUN598126"
  syncTimeout: 30
  autoExecute: false
  tickers: ["SPY","QQQ", "A", "AAL", "AAPL", "ABBV", "ABNB", "ABT", "ACGL", "ACN", "ADBE", "ADI", "ADM", "ADP", "ADSK", "AEE", "AEP", "AES", "AFG", "AFRM", "AFL", "AIG", "AIZ", "AJG", "AKAM", "ALB", "ALGN", "ALL", "ALLE", "AMAT", "AMCR", "AMD", "AMDL", "AME", "AMGN", "AMP", "AMT", "AMZN", "ANET", "AON", "AOS", "APA", "APD", "APH", "APTV", "ARE", "ARM", "ARKK", "ATO", "AVB", "AVGO", "AVY", "AWK", "AXON", "AXP", "AYI", "AZO", "BA", "BABA", "BAC", "BALL", "BAX", "BBWI", "BBY", "BDX", "BEN", "BG", "BIIB", "BIO", "BITX", "BK", "BKNG", "BKR", "BLDR", "BLK", "BMY", "BR", "BSX", "BWA", "BX", "BYND", "C", "CAG", "CAH", "CARR", "CAT", "CB", "CBOE", "CBRE", "CCI", "CCL", "CDNS", "CDW", "CE", "CEG", "CF", "CFG", "CHD", "CHRW", "CHTR", "CI", "CINF", "CL", "CLX",  "CMCSA", "CME", "CMG", "CMI", "CMS", "CNC", "CNP", "COF", "COIN", "COO", "COP", "COR", "COST", "CPAY", "CPB", "CPRT", "CPT", "CRL", "CRM", "CRWD", "CSGP", "CSX", "CTAS", "CTRA", "CTSH", "CTVA", "CVS", "CVNA", "CVX", "CZR", "D", "DAL", "DD", "DDOG", "DE", "DECK", "DELL", "DG", "DGX", "DHI", "DHR", "DIA", "DIS", "DLR", "DLTR", "DOC", "DOV", "DOW", "DPZ", "DRI", "DTE", "DUK", "DVA", "DVN", "DXCM", "EA", "EBAY", "ECL", "ED", "EFX", "EG", "EIX", "EL", "ELV", "EMN", "EMR", "ENPH", "EOG", "EPAM", "EQIX", "EQT", "ERIE", "ES", "ESS", "ETN", "ETR", "ETSY", "EVRG", "EW", "EXC", "EXPD", "EXPE", "EXR", "F", "FANG", "FAST", "FCX", "FDS", "FDX", "FE", "FFIV", "FICO", "FIS", "FITB", "FMC", "FOX", "FOXA", "FRT", "FSLR", "FTNT", "FTV", "GD", "GE", "GEHC", "GEN", "GEV", "GILD", "GIS", "GL", "GLW", "GM", "GNRC", "GOOG", "GOOGL", "GPN", "GRMN", "GS", "GWW", "HAL", "HAS", "HBAN", "HCA", "HD", "HIG", "HII", "HLT", "HOLX", "HON", "HOOD", "HPE", "HPQ", "HRL", "HSIC", "HST", "HSY", "HUBB", "HUM", "HWM", "IBM", "ICE", "IDXX", "IEX", "IFF", "ILMN", "INCY", "INTC", "INTU", "INVH", "IP", "IQV", "IR", "IRM", "ISRG", "IT", "ITW", "IVZ", "IWM", "J", "JBHT", "JBL", "JCI", "JD", "JKHY", "JNJ", "JPM", "KDP", "KEY", "KEYS", "KHC", "KIM", "KLAC", "KMB", "KMI", "KMX", "KO", "KR", "KVUE", "L", "LDOS", "LEN", "LH", "LHX", "LIN", "LKQ", "LLY", "LMT", "LNC", "LOW", "LRCX", "LULU", "LUV", "LVS", "LW", "LYB", "LYV", "MA", "MAA", "MAR", "MAS", "MCD", "MCHP", "MCK", "MCO", "MDB", "MDLZ", "MDT", "MET", "META", "METP", "MGM", "MHK", "MKC", "MKTX", "MLM", "MMM", "MNST", "MO", "MOH", "MOS", "MPC", "MPWR", "MRK", "MRNA", "MS", "MSI", "MSFT", "MSTR", "MTB", "MTCH", "MTD", "MU", "NCLH", "NDAQ", "NDSN", "NEE", "NEM", "NFLX", "NI", "NIO", "NKE", "NORW", "NSC", "NTAP", "NTRS", "NUE", "NVDA", "NVO", "NVR", "NWS", "NWSA", "NXPI", "O", "ODFL", "OKE", "OKLO", "OMC", "ON", "ORLY", "ORCL", "OTIS", "OXY", "PANW", "PAYC", "PAYX", "PCAR", "PCG", "PDD", "PEG", "PEP", "PFE", "PFG", "PG", "PGR", "PH", "PHM", "PKG", "PLD", "PLTR", "PM", "PNC", "PNR", "PNW", "PODD", "POOL", "PPG", "PPL", "PRU", "PSA", "PSX", "PTC", "PWR", "PYPL", "QCOM", "QRVO", "RCL", "REG", "REGN", "RF", "RIOT", "RIVN", "RJF", "RL", "RMD", "ROL", "ROP", "ROST", "RSG", "RTX", "RVTY", "SBAC", "SBUX", "SCHW", "SHOP", "SHW", "SJM", "SLB", "SMCI", "SNA", "SNPS", "SO", "SOXL", "SPG", "SPGI",  "SRE", "STE", "STLD", "STT", "STX", "STZ", "SWK", "SWKS", "SYK", "SYY", "T", "TAP", "TDG", "TDY", "TECH", "TEL", "TER", "TFC", "TFX", "TGT", "TJX", "TMO", "TMUS", "TNA", "TPR", "TQQQ", "TRGP", "TRMB", "TROW", "TRV", "TSCO", "TSLA", "TSM", "TSN", "TT", "TTWO", "TXN", "TXT", "TYL", "UAL", "UDR", "UHS", "ULTA", "UNH", "UNP", "UPS", "UPST", "URA", "URI", "USB", "V", "VICI", "VLO", "VMC", "VRSK", "VRSN", "VRTX", "VST", "VTR", "VZ", "WAB", "WAT", "WBD", "WDC", "WEC", "WELL", "WFC", "WHR", "WM", "WMB", "WMT", "WRB", "WST", "WTW", "WY", "WYNN", "XEL", "XOM", "XPEV", "XYL", "XYZ", "YUM", "ZBH", "ZBRA", "ZTS"]

risk:
  riskPerTradePct: 0.02   # 2% max risk per trade
  maxConcurrentTrades: 50
  # 👉 AÑADE ESTAS DOS LÍNEAS AQUÍ:
  tpMultiplier: 2.0  # Multiplicador del ATR para el Take Profit (Ej: 2.0 = 2 veces el ATR)
  slMultiplier: 1.0  # M
ai:
  geminiApiKey: "REDACTED_GOOGLE_API_KEY"
  enabled: true
  endpointBase: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key="

telegram:
  botToken: "REDACTED_TELEGRAM_BOT_TOKEN"
  chatId: "REDACTED_CHAT_ID"
  masterKey: "tu_llave_maestra"

strategies:
  global:
    simulationMode: false
    useAiAnalysis: false
  opening:
    bandWidth: 1.2
    callMinGap: -1.5
    callMaxGap: -4.0
    putMinGap: 1.5
    putMaxGap: 4.0
  continuation:
    callMinGap: 0.4
    callMaxGap: 1.8
    callWordenThreshold: 55.0
    putMinGap: -0.4
    putMaxGap: -1.8
    putWordenThreshold: 45.0